# Generated by Django 4.2.7 on 2025-10-26 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Короткое описание'),
        ),
    ]
